os: linux
dist: focal
language: c++
env:
  global:
       - DEBIAN_FRONTEND: noninteractive
addons:
  apt:
    packages:
        - wget
        - locales
        - python3-pip

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"
        - source .github/travis/common.sh
        - rm README.rst && make README.rst && .github/travis/git-check.sh
        - pip install git+https://github.com/antmicro/tuttest
        - tuttest README.rst unnamed0 | bash -
jobs:
  include:
    - stage: SymbiFlow
      install:
            - tuttest xc7/README.rst unnamed0 | bash -

      script:
            - tuttest xc7/README.rst unnamed1,unnamed2,unnamed3,unnamed4,unnamed5 | bash -
    - #
      install:
            - tuttest eos-s3/README.rst unnamed0 | bash -

      script:
            - tuttest eos-s3/README.rst unnamed1,unnamed2 | bash -

