os: linux
dist: focal
language: c++
env:
  global:
       - DEBIAN_FRONTEND: noninteractive
addons:
  apt:
    packages:
        - wget
        - locales
        - python3-pip

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"
        - pip install git+https://github.com/antmicro/tuttest
        - tuttest README.md unnamed0 | bash -
jobs:
  include:
    - stage: SymbiFlow
      install:
            - tuttest xc7/README.md unnamed0 | bash -

      script:
            - tuttest xc7/README.md unnamed1 | bash -
    - #
      install:
            - tuttest eos-s3/README.md unnamed0 | bash -

      script:
            - tuttest eos-s3/README.md unnamed1 | bash -

