os: linux
dist: focal
language: c++
env:
  global:
       - DEBIAN_FRONTEND: noninteractive
addons:
  apt:
    packages:
        - wget
        - locales
        - python3-pip

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"
        - source .github/travis/common.sh
        - rm README.rst && make README.rst && .github/travis/git-check.sh
        - pip install git+https://github.com/antmicro/tuttest
        - tuttest README.rst wget-conda | bash -ex -
jobs:
  include:
    - stage: SymbiFlow
      install:
            - export INSTALL_DIR=$PWD/../opt/symbiflow/xc7
            - tuttest xc7/README.rst xc7-setup-toolchain | bash -ex -

      script:
            - export INSTALL_DIR=$PWD/../opt/symbiflow/xc7
            - tuttest xc7/README.rst  xc7-prepare-env,xc7-counter,xc7-picosoc,xc7-litex,xc7-linux | bash -ex -

    - #
      install:
            - export INSTALL_DIR=$PWD/../opt/symbiflow/eos-s3
            - tuttest eos-s3/README.rst eoss3-setup-toolchain | bash -ex -

      script:
            - export INSTALL_DIR=$PWD/../opt/symbiflow/eos-s3
            - tuttest eos-s3/README.rst eoss3-prepare-env,eoss3-counter | bash -ex -

