name: xc7
channels:
  - symbiflow
dependencies:
  - symbiflow::symbiflow-yosys=0.8_6021_gd8b2d1a2
  - symbiflow::symbiflow-yosys-plugins=1.0.0.7_0117_g160b309
  - symbiflow::symbiflow-vtr=8.0.0.rc2_4003_g8980e4621
  - symbiflow::prjxray-db=0.0_0230_g485a837
  - symbiflow::prjxray-tools
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
