name: xc7
channels:
  - litex-hub
dependencies:
  - litex-hub::prjxray-tools
  - litex-hub::prjxray-db=0.0_0239_gd87c844=20201120_145821
  - litex-hub::openocd
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
